#!/usr/bin/env python3
"""patala/serializers/huggingface.py — Hugging Face dataset packaging.

Packages Pāṭala datasets for distribution via Hugging Face Hub.
Spec: https://huggingface.co/docs/hub/en/datasets

"Tools don't become truth. Their outputs become observations." — newbuild
"""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any


def create_dataset_card(title: str, description: str, license: str = "cc-by-sa-4.0",
                        authors: list[str] = None, tags: list[str] = None) -> str:
    """Create a Hugging Face dataset card (README.md for HF Hub)."""
    card = f"""---
language:
  - sa
  - en
license: {license}
tags:
  - sanskrit
  - digital-humanities
  - provenance
  - scholarly-database
{"  - " + "\\n  - ".join(tags) if tags else ""}
---

# {title}

{description}

## Citation

```bibtex
@dataset{{openpatala_{int(time.time())},
  title = {{{title}}},
  author = {{{", ".join(authors or ["OpenPatala"])}}},
  year = {{{time.strftime("%Y")}}},
  url = {{https://github.com/openpatala}}
}}
```

## Provenance

This dataset was generated by OpenPatala, the scholarly state machine for premodern texts.
Every record carries provenance information linking it to its source observations.
"""
    return card


def export_parquet_snapshot(snapshot: dict, output_dir: str) -> str:
    """Export a Pāṭala snapshot as Parquet files for HF Hub distribution.

    Per newbuildplayers: "Hugging Face is the obvious discovery/distribution surface
    for model-facing dataset releases."
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # Create dataset card
    card = create_dataset_card(
        title="OpenPatala Sanskrit Corpus",
        description="Scholarly state machine output for Sanskrit works with provenance",
        authors=["OpenPatala Project"],
    )
    (out / "README.md").write_text(card, encoding="utf-8")

    # Create metadata
    metadata = {
        "citation": f"OpenPatala {time.strftime('%Y')}",
        "homepage": "https://github.com/openpatala",
        "license": "cc-by-sa-4.0",
    }
    (out / "dataset_metadata.json").write_text(
        json.dumps(metadata, indent=2), encoding="utf-8"
    )

    return str(out)
